config/routes.rb
ReturnMockup::Application.routes.draw do
resources :products
  resources :pin_attributes

  root to: 'returns#index'
  get "home/index"

  resource :returns do
    get :index
    post :order_num
    get :review
    post :final_step
    get :all_returns
    get :shipping_label
    get :truncate_tables
    post :validate_orders
    get :canvas_test
    get :success_confirmation
    get 'show/:id'=>"returns#show", :as=>"show"
    get :return_orders
  end

  resource :attributes do
    get "/"=>"attributes#index"
    get 'all'=>"attributes#all"
    get 'edit/:id'=>"attributes#edit", :as=>"edit"
    patch '/:id', to: "attributes#update", :as=>"update"
  end

end

app/controllers/attributes_controller.rb
class AttributesController < ApplicationController
	def index
		@attributes = ReturnReasonAttribute.all
	end


	def new
		@attribute = ReturnReasonAttribute.new
		@parent_attributes = ReturnReasonAttribute.where("parent_id=?",0)
	end


	def edit
		@attribute = ReturnReasonAttribute.find(params[:id])
		@parent_attributes = ReturnReasonAttribute.where("parent_id=? and id!=?",0,params[:id])
		
	end


	def create
		@attribute = ReturnReasonAttribute.new(strong_params)
		if(@attribute.parent_id=="" || @attribute.parent_id.nil?)
			@attribute.parent_id = 0;
		end
		@attribute.code_name = @attribute.attr_name.gsub(/[^A-Za-z0-9]/i,"").downcase
		if(@attribute.save)
			redirect_to attributes_path
		else
			redirect_to new_attributes_path(@attribute)
		end
	end


	def update
		@attribute = ReturnReasonAttribute.find(params[:id])
		@attribute.assign_attributes(strong_params)

		if(@attribute.parent_id=="" || @attribute.parent_id.nil?)
			@attribute.parent_id = 0;
		end
		@attribute.code_name = @attribute.attr_name.gsub(/[^A-Za-z0-9]/i,"").downcase
		if(@attribute.save)
			redirect_to attributes_path
		else
			redirect_to new_attributes_path(@attribute)
		end

	end


	def all
		@attributes = ReturnReasonAttribute.all
	end


	private

	def strong_params
		params.require(:return_reason_attribute).permit(:attr_name, :parent_id,:display_order,:attr_type)
	end
end

app/views/attributes/all.html.erb
<%= debug(@attributes) %>

<hr />

app/views/attributes/edit.html.erb
<%= form_for @attribute,url: update_attributes_path(@attribute[:id]) do |f| %>
<%= f.label :attr_name, :name %>
<%= f.text_field :attr_name %>
<br>
<%= f.label :parent_id, :parent_attribute %>
<%= f.collection_select :parent_id, @parent_attributes, :id, :attr_name, :include_blank=>"Select an option or leave blank" %>
<br>
<%= f.label :display_order %>
<%= f.text_field :display_order %>
<br />
<%= f.label :attr_type, :type %>

<%= f.select( :attr_type, [["Group",1],["Selection",2]]) %>
<br />
<%= f.submit "Save" %>
<% end %>

app/views/attributes/index.html.erb
<%= link_to "Add New Attribute", new_attributes_path %>

<table>
<thead>
	<tr>
		<th>ID</th>
	<th>
		Name
	</th>
	<th>Code Name</th>
	<th>
		Display Order
	</th>
	<th>
		Edit
	</th>
	<th>
		Delete
	</th>
	</tr>
</thead>
<tbody>
<% @attributes.each do |a| %>
	<tr>
		<td><%= a[:id] %></td>
		<td><%= a[:attr_name]%></td>
		<td><%= a[:code_name]%></td>
		<td><%= a[:display_order]%></td>
		<td><%= link_to "Edit",edit_attributes_path(a[:id]) %></td>
		<td>Delete</td>
	</tr>
<% end %>

</tbody>

</table>

app/views/attributes/new.html.erb
<%= form_for @attribute,url: attributes_path do |f| %>
<%= f.label :attr_name, :name %>
<%= f.text_field :attr_name %>
<br>
<%= f.label :parent_id, :parent_attribute %>
<%= f.collection_select :parent_id, @parent_attributes, :id, :attr_name, :prompt=>"Select an option or leave blank" %>
<br>
<%= f.label :display_order %>
<%= f.text_field :display_order %>
<br />
<%= f.label :attr_type, :type %>
<%= f.select(:attr_type, [["Group",1],["Selection",2]],prompt: "select type") %>
<br />
<%= f.submit "Add" %>
<% end %>