config/routes.rb
ReturnMockup::Application.routes.draw do
resources :products
  resources :pin_attributes

  root to: 'returns#index'
  get "home/index"

  resource :returns do
    get :index
    post :order_num
    get :review
    post :final_step
    get :all_returns
    get :shipping_label
    get :truncate_tables
    post :validate_orders
    get :canvas_test
    get :success_confirmation
    get 'show/:id'=>"returns#show", :as=>"show"
    get :return_orders
  end

  resource :attributes do
    get "/"=>"attributes#index"
    get 'all'=>"attributes#all"
    get 'edit/:id'=>"attributes#edit", :as=>"edit"
    patch '/:id', to: "attributes#update", :as=>"update"
  end

end

app/models/pin_attribute.rb
class PinAttribute < ActiveRecord::Base
	has_many :child_attributes, :class_name=> "PinAttribute", :foreign_key=>"parent_id"
end

app/controllers/pin_attributes_controller.rb
class PinAttributesController < ApplicationController
  before_action :set_pin_attribute, only: [:show, :edit, :update, :destroy]

  # GET /pin_attributes
  # GET /pin_attributes.json
  def index
    @pin_attributes = PinAttribute.where("parent_id=?",0)
  end

  # GET /pin_attributes/1
  # GET /pin_attributes/1.json
  def show
  end

  # GET /pin_attributes/new
  def new
    @pin_attribute = PinAttribute.new
    @parent_pin_attributes = PinAttribute.where("parent_id=?",0)
  end

  # GET /pin_attributes/1/edit
  def edit
    @parent_pin_attributes = PinAttribute.where("parent_id=?",0)
  end

  # POST /pin_attributes
  # POST /pin_attributes.json
  def create

    pin_params = pin_attribute_params
      if pin_params[:parent_id].empty?
        pin_params[:parent_id]=0
      end

    @pin_attribute = PinAttribute.new(pin_params)

    respond_to do |format|
      if @pin_attribute.save
        format.html { redirect_to @pin_attribute, notice: 'Pin attribute was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin_attribute }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pin_attributes/1
  # PATCH/PUT /pin_attributes/1.json
  def update
    respond_to do |format|
      pin_params = pin_attribute_params
      if pin_params[:parent_id].empty?
        pin_params[:parent_id]=0
      end

      if @pin_attribute.update(pin_params)
        format.html { redirect_to @pin_attribute, notice: 'Pin attribute was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pin_attributes/1
  # DELETE /pin_attributes/1.json
  def destroy
    @pin_attribute.destroy
    respond_to do |format|
      format.html { redirect_to pin_attributes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin_attribute
      @pin_attribute = PinAttribute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_attribute_params
      params.require(:pin_attribute).permit(:name,:parent_id,:fill)
    end
end

app/helpers/pin_attributes_helper.rb
module PinAttributesHelper
end

app/views/pin_attributes/_form.html.erb
<%= form_for(@pin_attribute) do |f| %>
  <% if @pin_attribute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin_attribute.errors.count, "error") %> prohibited this pin_attribute from being saved:</h2>

      <ul>
      <% @pin_attribute.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :parent %>
    <%= f.collection_select :parent_id, @parent_pin_attributes, :id, :name, :include_blank=>"Select an option or leave blank" %>
  </div>
  <div class="field">
    <%= f.text_field :fill, :id=>"color_fill" %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
    $("#color_fill").spectrum({
      showInput: true,
      showAlpha:true,
      change: function(color) {
        $("#color_fill").val(color.toHexString());
      }
    });
</script>

app/views/pin_attributes/edit.html.erb
<h1>Editing pin_attribute</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin_attribute %> |
<%= link_to 'Back', pin_attributes_path %>

app/views/pin_attributes/index.html.erb
<h1>Listing Pin Attributes</h1>
<%= link_to 'New Pin attribute', new_pin_attribute_path %>
<table class="table">
  <thead>
    <tr>
      <th>Group Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pin_attributes.each do |pin_attribute| %>
      <tr>
        <td><%= pin_attribute.name %></td>
     
        <td><%= link_to 'Show', pin_attribute %></td>
        <td><%= link_to 'Edit', edit_pin_attribute_path(pin_attribute) %></td>
        <td><%= link_to 'Destroy', pin_attribute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% if(pin_attribute.child_attributes.length) %>
      
         <tr><th style="text-align:center;">Child attributes</th><td colspan="3"></td></tr>
         <% pin_attribute.child_attributes.each do |child_attr| %>
         <tr>
          <td colspan="2" style="text-align:center"><%= child_attr.name %></td>
            <td><%= link_to 'Edit', edit_pin_attribute_path(child_attr) %></td>
            <td><%= link_to 'Destroy', child_attr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         </tr>
         <% end %>
        
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin attribute', new_pin_attribute_path %>

app/views/pin_attributes/new.html.erb
<h1>New pin_attribute</h1>

<%= render 'form' %>

<%= link_to 'Back', pin_attributes_path %>

app/views/pin_attributes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pin_attribute.name %>
</p>

<%= link_to 'Edit', edit_pin_attribute_path(@pin_attribute) %> |
<%= link_to 'Back', pin_attributes_path %>