config/routes.rb
ReturnMockup::Application.routes.draw do
resources :products
  resources :pin_attributes

  root to: 'returns#index'
  get "home/index"

  resource :returns do
    get :index
    post :order_num
    get :review
    post :final_step
    get :all_returns
    get :shipping_label
    get :truncate_tables
    post :validate_orders
    get :canvas_test
    get :success_confirmation
    get 'show/:id'=>"returns#show", :as=>"show"
    get :return_orders
  end

  resource :attributes do
    get "/"=>"attributes#index"
    get 'all'=>"attributes#all"
    get 'edit/:id'=>"attributes#edit", :as=>"edit"
    patch '/:id', to: "attributes#update", :as=>"update"
  end

end

app/controllers/returns_controller.rb
class ReturnsController < ApplicationController
	protect_from_forgery :only=>[:order_num,:review,:final_step,:success]
	def index
		session.delete(:order_num)
	end

	def order_num
		if(params.has_key?(:order_num))
			order_number = params[:order_num]
		elsif(session.has_key?(:order_num))
			order_number = session[:order_num]
		else
			order_number = 0;
		end

	  	@order = Order.where("order_num = ?", params[:order_num]).take
	  
	  	if(@order.nil?)
	  		flash[:error] = "The order number is invalid"
	  		redirect_to action:"index", controller:"returns" and return
  			#add another check for when time of when order was created is more than 40 days
  			#add another check if all items have been returned
		#elsif (DateTime.now.to_date-@order[:created_at].to_date).to_i > 40
		#	flash[:error] = "You cannot return items for orders older than 40 days"
		#	redirect_to action:"index", controller:"returns" and return
  		else
  			can_continue = false
  			# in here, want to get all items that have been put for return and all items that have shipped to compare
  			return_items_temp = ReturnItems.select("return_items.order_item_id").where("order_num=?",params[:order_num]).group(:order_item_id).count
  			@order.order_items.each do |obj|
  				if(return_items_temp.has_key?(obj[:id]))
	  				if(obj[:quantity] - return_items_temp[obj[:id]] > 0)
	  					can_continue = true
	  					break
	  				end
  				elsif obj[:quantity]>0
  					can_continue = true
  					break

  				end
  			end

  			if(!can_continue)
  				flash[:error] = "there are no more items to return"
  				redirect_to action: "index", controller: "returns" and return
  			end
  			#ReturnItems.select("return_items.order_item_id,order_items.quantity").where("return_items.order_num=?",params[:order_num]).joins(:order_item).group("return_items.order_item_id").count("return_items.order_item_id")
	  	end

	  	# if everything is valid, then we should be able to get here

	  	#save order number in session
	  	session[:order_num] = params[:order_num]

  	end
  	def validate_orders
  		errors = Array.new
 		#@options = ReturnReasonAttribute.where("parent_id=?",0)
  		#make sure order number was passed
  		if(!session.has_key?(:order_num))
  			errors << "the order number is invalid."
  			flash[:errors] = errors
  			redirect_to action: "index",controller: "returns" and return
  		end

	  	@order = Order.where("order_num = ? ",session[:order_num]).take
	  	if(@order.nil?)
	  		errors << "The order number is invalid."
	  		flash[:errors] = errors
	  		redirect_to action:"index", controller:"returns" and return
	  	end

	  	if(params[:order_items].empty?)
	  		errors << "you must select at least one item to return"
	  		flash[:errors] = errors
	  		redirect_to action:"index", controller:"returns" and return
	  	end

	  	redirect_back = false;
	  	valid_items = true;
	  	#only want the items that actually have a value in them
	  	return_order_items = params[:order_items]
	  	@order_items = OrderItem.find(return_order_items)

	  	@counts = Hash.new(0)
	  	return_order_items.each {|oid| @counts[oid.to_i]+=1}
	  	

	  	@order_items.each do |item|
	  		qty_r = @order.quantity_returns.where(order_item_id: item.id).first
	  		quantity = (qty_r.nil?) ? 0 : ( (qty_r[:quantity]==nil) ? 0 : qty_r[:quantity] )
	  		# make sure order item exists for the order
	  		if item[:order_id]!=@order[:id] && valid_items 
	  			valid_items = false;
	  			redirect_back = true;
	  			errors << "some selected items do not exist for the order "+session[:order_num]
	  		end
	  		# make sure number of items to be returned is less than or equal to the quantity bought minus items already returned for the same product
	  		if (item[:quantity] - (quantity || 0) ) < @counts[item[:id]]
	  			errors << "invalid quantity amount for " + item[:product_name];
	  			redirect_back = true
	  		end
	  	end

	  	if(return_order_items.empty?)
	  		errors << "you must select at least one item to return"
	  		redirect_back = true;
	  	end
	  	
	  	#render_order_num = true;
	  	if(redirect_back)
	  		flash[:errors] = errors
	  		#render :to_step_1 #this will be used in case we want to redirect
	  		redirect_to action:"order_num",controller:"returns" and return
	  	end
	  	# order items have been validated, store in session
	  	session[:order_items_count] = @counts
	  	session[:return_items] = return_order_items
	  	session[:validated] = true
	  	redirect_to action:"review",controller:"returns" and return
  	
  	end

	def review

  		@options = ReturnReasonAttribute.where("parent_id=?",0).order("display_order")

  		@attributes = PinAttribute.includes([:child_attributes]).where("parent_id=?",0)

  		
  		

  		#make sure order number was passed
  		if(!session.has_key?(:order_num))
  			flash[:error] = "the order number is invalid."
  			redirect_to action: "index",controller: "returns" and return
  		end

	  	@order = Order.where("order_num = ? ",session[:order_num]).take
	  	if(@order.nil?)
	  		flash[:error] = "The order number is invalid."
	  		redirect_to action:"index", controller:"returns" and return
	  	end

	  	if((session.has_key?(:validated) || session[:validated]==false))
  			#validate here
  			if(session.has_key?(:return_items))
  				if( !validate_order_items(session[:order_num], session[:return_items]) )
  					redirect_to action: "index", controller: "returns" and return
  				end
  			else
  				redirect_to action: "index",controller: "returns" and return
  			end	
		else
			session.delete(:validated)	
  		end

	  	
	  
	  	@order_items = OrderItem.find(session[:return_items])
	  	@counts = session[:order_items_count]
	  	


	end #end validate_step_one

	def validate_final_step

	end




	def final_step
		if(params.has_key?(:pin_attributes))
			pin_attributes = params[:pin_attributes]
		else
			pin_attributes = Hash.new
		end
		
		return_attributes = params[:return_attributes]
		@return_attributes_ids = []
		return_attributes.each do |key,list|
			list.each do |skey, slist|
				@return_attributes_ids += slist.map(&:to_i)
			end
		end
		# need to find out if they chose fit issues checkbox so we can render the checkbox
		#@reasons_selected = ReturnReasonAttribute.where("id IN (:ids) and code_name = :cd",{ids: @return_attributes_ids,cd: "fitissues"})
		#if(@reasons_selected.any? && !params.has_key?("fit_change_submit"))
		#	render :fit_issues and return
		#end
		#options for review
	 	@options = ReturnReasonAttribute.where("parent_id=?",0)
	 	#this wont be used anymore
	 	heel_height = (params.has_key?(:heel_height)) ? params[:heel_height] : 0;
	 	height_feet = (params.has_key?(:feet)) ? params[:feet] : 0
	 	height_inches = (params.has_key?(:inches)) ? params[:inches] : 0

		return_items = Array.new
		@all_errors = Array.new
		@order = Order.find(params[:order_id])
		return_order = ReturnOrders.new(order_id: params[:order_id],order_num: params[:order_num],
			return_status: 0, heel_height: heel_height, height_feet: height_feet, height_inches: height_inches)

		return_items = params[:order_items]
		@order_items = OrderItem.find(params[:order_items])

		@counts = Hash.new(0)
	  	return_items.each {|oid| @counts[oid]+=1}
	  	
	  	
	  	

		total_amount = 0.00;
		# here we valdiate that the amount of products being returned is valid
		@order_items.each do |item|
			iid = item[:id].to_s
			if(@counts[item[:id].to_s] > item[:quantity])
				@all_errors << "invalid quantity amount returned for product " + item[:product_name]
				break 
			end
			#iterate depending on how many they choose to return of the same product
			(1..@counts[item[:id].to_s]).to_a.each do |times| 
				return_item = ReturnItems.new(order_num: @order[:order_num],
					order_id: @order[:id], product_name: item[:product_name],
					amount_refunded: item[:price],
					status: "pending", quantity: 1,order_item_id: item[:id])
				#for each attribute selected for this product
				if(!return_attributes[iid][times.to_s].nil?)
					return_attributes[item[:id].to_s][times.to_s].each do |attr_id|
						return_item.return_order_attributes << ReturnOrderAttribute.new(return_reason_attribute_id: attr_id)
					end
				end
				if (pin_attributes.has_key?(iid))
					if(pin_attributes[iid].has_key?(times.to_s))

						if(pin_attributes[iid][times.to_s].has_key?(:front))
							pin_attributes[iid][times.to_s][:front].each do |pin|
								pin_arr = pin.split("_")
								# after splitting, the array must be length of 6
								if(pin_arr.length==6) 
									return_item.return_item_pins << ReturnItemPin.new(pos_x: pin_arr[1],
										pos_y: pin_arr[2],
										radius: pin_arr[3],pin_attribute_id_id: pin_arr[0],
										canvas_width: pin_arr[4], canvas_height: pin_arr[5], image_type: "front")
								end
							end
						end

						if(pin_attributes[iid][times.to_s].has_key?(:back))
							pin_attributes[iid][times.to_s][:back].each do |pin|
								pin_arr = pin.split("_")
								# after splitting, the array must be length of 6
								if(pin_arr.length==6) 
									return_item.return_item_pins << ReturnItemPin.new(pos_x: pin_arr[1],
										pos_y: pin_arr[2],
										radius: pin_arr[3],pin_attribute_id_id: pin_arr[0],
										canvas_width: pin_arr[4], canvas_height: pin_arr[5], image_type: "back")
								end
							end
						end

						#return_item.return_item_pins << ReturnItemPin.new()
					end
				end

				return_order.return_items << return_item
				total_amount += item[:price]
			end

			# if no break then that means there where no errors
			#item[:amount_returned] += @cofunts[item[:id].to_s]
			#order_items_to_save << item
			
			
		end
		
		return_order[:amount_to_refund] = total_amount
	

		if(@all_errors.length<=0)
			if(return_order.save)
				return_order.save

				@counts.each do |k,v|
					qr = QuantityReturn.find_or_initialize_by(order_id: @order.id, order_item_id: k)
					if(qr.quantity.nil?)
						qr.quantity = v
					else
						qr.quantity += v
					end
					qr.save
				end
				#OrderItem.transaction do

app/views/returns/all_returns.html.erb
<%= debug(@orders) %>

<br />
<%
#@order_items.find(1).assign_attributes(amount_returned: 5)
%>
<%= debug(@order_items) %>

<hr />

<%= debug(@return_orders) %>
<br />

<%= debug(@return_items) %>

<br />

<%= debug(@quantity_returns) %>

<br />

<%= debug(@return_order_attributes) %>
<hr />


<%= debug(@return_item_pins) %>

<%= debug(@quantity_returns) %>

app/views/returns/final_step.html.erb
<h1 class="text-center">Returns &amp; Exchanges</h1>
<hr />

<div id="main-container">
	<div id="header">
		<ul id="links-top">
			<li class="active link-one"><a class="button"><span class="number">1</span> Choose Items to Return</a></li>
			<li class="active link-two content-before"><span class="number">2</span> Review and Confirm</li>
			<li class="active link-three content-before content-after"><span class="number">3</span> Print Shipping Label</li>
		</ul>
	</div>
	<div id="content">
		your return is all set. please print you shipping label
		(more instructions will go here)
	</div>
</div>

app/views/returns/fit_issues.html.erb
<%= form_tag({controller: "returns",action: "final_step"}, method: "post",id: "fit-issues-form") do |f| %>
<input type="hidden" name="fit_change_submit" value="1" />
<% end %>

app/views/returns/index.html.erb
<div id="header">
	<img src="<%= image_url("returnsBar_1.gif") %>" />
		
</div>
<h4 class="index-page-header">We understand that not every purchase will be<br /> the perfect fit, so we've made returns easy.</h4>
<div class="form-wrapper">
<h3 class="form-header">Enter your order number below:</h3>

<% if(flash[:error]) %>
<div class="red flash-error"><p><%= flash[:error] %></p></div>
<% end %>
<div class="error red"></div>
<%= form_tag({controller:"returns", action: "order_num"},method: "post",id: "order-return-form") do %>
<div class="field-container">
<input type="text" name="order_num" placeholder="Order Number" />

<button type="submit"><img src="<%= image_url("arrow_Submit.gif")%>" /></button>
</div>
<% end %>
<div class="links-block">
	<p>Or Sign in to Find Your Order</p>
	<p>Help Me Find My Order Number</p>
</div>
</div>

<div class="step-one-bottom-text">
Items are gladly accepted in their new, unused condition with<br />garment tags attached within 30 days of delivery date.
</div>



<script type="text/javascript">
	$("#order-return-form").on("submit",function() {
		var input = $(this).find("input[name='order_num']");
		if(input.length) {
			if(input.val()=="") {
				$("div.flash-error").empty();
				$("div.error").html("field cannot be blank");
				return false;
			} else if(!input.val().match(/[0-9]{1,}/)) {
				$("div.flash-error").empty();
				$("div.error").html("enter a valid order number");
				return false;
			}

		}
	});
</script>

app/views/returns/order_num.html.erb
<% @return_items = ReturnItems.select("return_items.order_item_id").where("order_num=?",params[:order_num]).group(:order_item_id).count %>


<div id="header">
	<div id="sub-header"><img src="<%= image_url("returnsBar_1.gif") %>" /></div>
	<div id="stepbar" style="background:url('<%= image_url("stepBar_1.gif")%>')">
		<span id="sb-one" class="linkbar active"><span class="number">1</span><span class="bar-text">Select Item(s) to Return</span></span>
		<span id="sb-two" class="linkbar"><span class="number">2</span><span class="bar-text">Select Return Reason(s)</span></span>
		<span id="sb-three" class="linkbar"><span class="number">3</span><span class="bar-text">Confirm and Ship</span></span>
	</div>
	<!--<img src="<%= image_url("stepBar_1_1.gif") %>" />-->
		
</div>

<div id="main-container" class="main-cont-step-one">
	
<div id="sidebar">
	<div class="sub-sidebar-section-info">
	
		<div class="sub-section-header"><b>Order Number:</b></div>
	
		<span><%= @order[:order_num]%></span>
	</div>
	<div class="sub-sidebar-section-info">
	
		<div class="sub-section-header"><b>Order Date:</b></div>
	
		<span><%= @order.created_at.strftime("%B %d, %Y") %></span>
	</div>
	<div class="sub-sidebar-section-info">
	
		<div class="sub-section-header"><b>Recipient:</b></div>
	
		<span><%= @order.full_name %></span>
	</div>
	
	<div class="sub-sidebar-section-info">
	
		<div class="sub-section-header"><b>Payment Method:</b></div>
	
		<span>
			Card ending in 5002
		<br />
		Total <%= number_to_currency(@order[:amount]) %>
		</span>
	</div>
	
	
</div>
	<div id="content">
		<% if (@all_errors) %>
		<div class="red"><%= @all_errors.join("<br />").html_safe %></div>
		<% end %>

		<h3>Please Select the Item(s) You Would Like to Return</h3>
		<% #test_qty_returned = OrderItemQuantityReturned.where(:order_id=>1,:order_item_id=>1).first %>

		<%= form_tag({controller:"returns", action: "validate_orders"},method: "post",id: "items-form") do %>
			<input type="hidden" name="order_id" value="<%= @order[:id] %>" />
			<input type="hidden" name="order_num" value="<%= @order[:order_num] %>" />
			<input type="hidden" name="review_page" value="true" />
			<% @order.order_items.each do |item| %>
				<% qty_r = @order.quantity_returns.where(order_item_id: item.id).first %>
		
				<% quantity_order_item = (qty_r.nil?) ? 0 : ( (qty_r[:quantity]==nil) ? 0 : qty_r[:quantity] ) %>
		
				<% if((item[:quantity] - (quantity_order_item || 0) )>0) %>
					<% (1..(item[:quantity] - (quantity_order_item || 0) )).to_a.each do |times| %>
						<div class="inline-block product-order-item">
							<div class="img-container">
								<img width="260" height="390" src="<%= image_url(item.product.image_front) %>" />
								<input type="checkbox" name="order_items[]" value="<%= item[:id] %>" />
								<label class="checkbox-label"></label>
								<img class="checkbox-label-img" width="20" height="17" src="<%= image_url("CHECK.png") %>" />
							</div>
							<div class="prod-desc">
								<p class="sub-section-header"><b><%= item.product_name %></b></p>
								<p class="sku-title"><%= item.product.sku%></p>
								<p><%= number_to_currency(item[:price]) %></p>
								<br>
							</div>
						</div>
					<% end %>
				<% end %>
			<% end %>
		<% end %>

	</div>
	<div id="footer" class="step-1-footer">
		<a href="<%= returns_path %>" class='previous-options no-background-color'><img src="<%= image_url("arrow_Previous.gif") %>" /></a>
		<button type="submit" id="submit-btn" class="next-btn" disabled><img src="<%= image_url("arrow_Continue.gif") %>" /></button>
	</div>
</div>

<script type="text/javascript">
	
	$("#items-form select.size-select").hide();
	$("#items-form").on("change","input[type='checkbox']",function(e) {
		
		if($("#items-form").find("input[type='checkbox']:checked").length) {
			$("#items-form button").prop("disabled",false);
		}
		else {
			$("#items-form button").prop("disabled",true);
		}
		//if($(this).find("input["))
	});

	$("#items-form").on("change","select",function(e) {
		
		if($(this).val()==2) {
			$(this).next("select.size-select").show();
		} else {
			$(this).next("select.size-select").hide();
		}

		


	});

	$("#items-form input[type='checkbox']").on("change",function(e) {
		// there is some checked checkboxes
		if($("#items-form input[type='checkbox']:checked").length) {
			$("#submit-btn").prop("disabled",false);
		} else {
			$("#submit-btn").prop("disabled",true);
		}
	});

	$("#submit-btn").on("click",function() {
		$("#items-form").submit();
	});

	$(".checkbox-label").on("click",function(e) {
		//console.log("test");
		e.stopPropagation();
		var label = $(this);
		if(label.hasClass("active")) {
			label.removeClass("active");
			label.prev("input").prop("checked",false);
			label.next("img").removeClass("active");
		} else {
			label.addClass("active");
			label.prev("input").prop("checked",true);
			label.next("img").addClass("active");
		}
		console.log($("#items-form").find("input[type='checkbox']:checked").length);
		if($("#items-form").find("input[type='checkbox']:checked").length) {
			$("#submit-btn").prop("disabled",false);
		}
		else {
			$("#submit-btn").prop("disabled",true);
		}

		//console.log($("#items-form").find("input[type='checkbox']:checked"));
	});


	$(".product-order-item .img-container").on("click",function(e) {
		//console.log("checkbix label in img container");
		e.stopPropagation();
		var label = $(this).find(".checkbox-label");
		if(!label.length) {return;}
		if(label.hasClass("active")) {
			label.removeClass("active");
			label.prev("input").prop("checked",false);
			label.next(".checkbox-label-img").removeClass("active");
		} else {
			label.addClass("active");
			label.prev("input").prop("checked",true);
			label.next(".checkbox-label-img").addClass("active");
		}
		console.log($("#items-form").find("input[type='checkbox']:checked").length);
		if($("#items-form").find("input[type='checkbox']:checked").length) {
			$("#submit-btn").prop("disabled",false);
		}
		else {
			$("#submit-btn").prop("disabled",true);
		}
	});
</script>

app/views/returns/return_orders.html.erb
<div>

<table class="table">
	<thead>
		<tr>
			<th>Return ID</th>

			<th>Order Number</th>
			<th>View</th>
		</tr>
	</thead>
<% @return_orders.each do |obj| %>
	<tr>
		<td><%= obj.id %></td>
		<td><%= obj.order_num %></td>
		<td><%= link_to 'Show',show_returns_path(obj) %></td>
	</tr>
<% end %>

</table>
</div>

app/views/returns/shipping_label.html.erb
<div id="main-container">
	<div id="header">
		<div id="sub-header"><img src="<%= image_url("returnsBar_1.gif") %>" /></div>
	<div id="stepbar" style="background:url('<%= image_url("stepBar_3.gif")%>')">
		<span id="sb-one" class="linkbar active"><span class="number">1</span><span class="bar-text">Select Item(s) to Return</span></span>
		<span id="sb-two" class="linkbar active"><span class="number">2</span><span class="bar-text">Select Return Reason(s)</span></span>
		<span id="sb-three" class="linkbar active"><span class="number">3</span><span class="bar-text">Confirm and Ship</span></span>
	</div>
	</div>


	<div id="success-content">
		<h2 class="thank-you-header">Thank You</h2>
		<h3>Your Return has been Processed</h3>
		<span class="instructions-message">
			<div>Once received, all correctly returned products will be refunded within 10 business days.</div>
			<div>If you have any questions, please email <a class="email-link no-hover-effect" href="mailto:customercare@tadashishoji.com">customercare@tadashishoji.com</a></div>
			
			<p class="returns-policy"><a class="no-hover-effic" href="#" target="_blank">Return Policy</a></p>
		</span>
		
		<div class="final-steps-section">
			<div class="container-left">
				<img src="<%= image_path("icon_ShippingLabel.gif") %>" />
			</div>
			<!--international shipping will be responsible for returning their own products with no shipping label-->
			<div class="container-right">
				<div><img src="<%= image_path("arrow_PrintShipping.gif") %>" /></div>
				<div class="shipping-instructions-content">Your refund will be reduced by the return shipping fee of $10.</div>

			</div>
		</div>

		<div class="final-steps-section">
			<div class="container-left">
				<img src="<%= image_path("icon_OpenBox.gif") %>" />
			</div>
			<div class="container-right">
				<div><h5>Put the items your are returning in a box.</h5></div>
				<div class="shipping-instructions-content">Seal all sides of the box with packing tape.</div>

			</div>
		</div>

		<div class="final-steps-section">
			<div class="container-left">
				<img src="<%= image_path("icon_ClosedBox.gif") %>" />
			</div>
			<div class="container-right">
				<div><h5>Apply the return label to the outside of the box.</h5></div>
				<div class="shipping-instructions-content">Ideally covering any old shipping labels.</div>

			</div>
		</div>

		<div class="final-steps-section">
			<div class="container-left">
				<img src="<%= image_path("icon_UPS.gif") %>" />
			</div>
			<div class="container-right">
				<div><h5>Drop off your package.</h5></div>
				<div class="shipping-instructions-content">Find your <a href="#" target="_blank" class="email-link no-hover-effect">nearest UPS dropoff.</a></div>

			</div>
		</div>
		

		<div id="footer">
			
			<a href="#" id="finish-return" class="no-background-color"><img src="<%= image_url("arrow_ContinueShop.gif") %>" /></a>
			</div>

	</div>

	
</div>

app/views/returns/success_confirmation.html.erb
<div id="main-container">
	
<div id="header">
		<img src="<%= image_url("stepBar_3.gif") %>" />
	</div>

	<div id="success-content">
		<h2 class="thank-you-header">Thank You</h2>
		<h3>Your Return has been Processed</h3>
		<span class="instructions-message">
			<div>Once received, all correctly returned products will be refunded within 10 business days.</div>
			<div>If you have any questions, please email <a class="email-link no-hover-effect" href="mailto:customercare@tadashishoji.com">customercare@tadashishoji.com</a></div>
			
			<p class="returns-policy"><a class="no-hover-effic" href="#" target="_blank">Return Policy</a></p>
		</span>
		<div class="rma-box">
			<div id="sidebar">
				<div class="sub-sidebar-section-info">
	
					<div class="sub-section-header"><b>Confirmation Number:</b></div>
	
					<span>100874683</span>
				</div>
				<div class="sub-sidebar-section-info">
				
					<div class="sub-section-header"><b>Tracking Number:</b></div>
				
					<span>100874683</span>
				</div>
				<div class="sub-sidebar-section-info">
				
					<div class="sub-section-header"><b>Return Date:</b></div>
				
					<span><%= @return.created_at.strftime("%B %d, %Y") %></span>
				</div>
				
				<div class="sub-sidebar-section-info">
				
					<div class="sub-section-header"><b>Recipient:</b></div>
				
					<span>
						<%=  @order.full_name %>
					</span>
				</div>
				<div class="sub-sidebar-section-info">
				
					<div class="sub-section-header"><b>Payment Method:</b></div>
				
					<span>
						Card ending in 5002
						<br />
						Total <%= number_to_currency(@order[:amount]) %>
					</span>
				</div>
			</div>
			<div id="content">
			
				<% @return.return_items.each do |item| %>
				<div class="inline-block product-order-item">
					<div class="img-container">
					<img width="260" height="390" src="<%= image_url(item.order_item.product.image_front)%>" />
					</div>
					<div class="prod-desc">
								<p class="sub-section-header"><b><%= item.order_item.product.name %></b></p>
								<p><%= item.order_item.product.sku%></p>
								<p><%= number_to_currency(item.order_item.price) %></p>
								<br>
							</div>
					
				

			</div>
			<% end %>

		</div>
		
		<div id="footer">			
			<a href="<%= success_confirmation_returns_path %>" id="continue-btn" class="next-btn no-background-color">
				<img src="<%= image_url("arrow_ContinueShop.gif") %>" />
			</a>
		</div>
	</div>

	
</div>

</div>

app/views/returns/to_step_1.html.erb
<%= form_tag({controller:"returns", action: "order_num"},method: "post", id: "autosubmit") do  do %>
<input type="hidden" name="order_num" value="<%= @order[:order_num]%>" />
<% end %>

<script type="text/javascript">
window.onload = function() {
	document.getElementById("autosubmit").submit();
}
</script>